var keyMirror = require('keymirror');

module.exports.actions = keyMirror({
  REGDEM_SET_OBJEKT_ID: null,
  REGDEM_CLOSE_EDITOR: null,
  REGDEM_EXPAND_EDITOR: null,
  REGDEM_FETCH_OBJEKT_POSITIONS: null,
  REGDEM_SELECT_EXTRA_EGENSKAP: null,
  REGDEM_FETCH_OBJEKT_TYPES: null,
  REGDEM_SET_INPUT_VALUE: null,
  REGDEM_EXECUTE_SEARCH: null,
  REGDEM_RESET_APP: null,
  REGDEM_CLOSE_LIST: null,
  REGDEM_SHOW_LIST: null,
  REGDEM_HIGHLIGHT_MARKER: null,
  REGDEM_ADD_GEOM_START: null,
  REGDEM_ABORT_GEOM_ADD: null,
  REGDEM_ADD_GEOM_END: null,
  REGDEM_GET_CURRENT_LOCATION: null,
  REGDEM_LOCATION_HAS_BEEN_SET: null,
  REGDEM_GO_BACK_AND_RESET: null,
  REGDEM_UPDATE_VAL_MESSAGE: null,
  REGDEM_UPDATE_ENUM_VALUE: null,
  REGDEM_UPDATE_FIELD_VALUE: null,
  REGDEM_UPDATE_VALIDATOR_RESPONSE: null,
  REGDEM_MAKE_THIS_STATE_ACTIVE: null,
  REGDEM_SET_PREV_SELECTED_INDEX: null,
  REGDEM_TERMINATE_STATE_AND_RESET: null,
  REGDEM_UPDATE_WRITE_STATUS: null,
  REGDEM_UPDATE_PROGRESS_STATUS: null,
  REGDEM_HAS_SCROLLED_TO_TOP: null
});

module.exports.values = {
  REGDEM_SIZE_DESKTOP: 800,
  REGDEM_LOCAL_API_SERVER: '/api/'
};
