var keyMirror = require('keymirror');

module.exports.actions = keyMirror({
  REGDEM_SET_OBJEKT_ID: null,
  REGDEM_CLOSE_EDITOR: null,
  REGDEM_EXPAND_EDITOR: null,
  REGDEM_FETCH_OBJEKT_POSITIONS: null,
  REGDEM_SELECT_EXTRA_EGENSKAP: null,
  REGDEM_FETCH_OBJEKT_TYPES: null,
  REGDEM_SET_INPUT_VALUE: null,
  REGDEM_EXECUTE_SEARCH: null,
  REGDEM_RESET_APP: null,
  REGDEM_CLOSE_LIST: null,
  REGDEM_SHOW_LIST: null,
  REGDEM_HIGHLIGHT_MARKER: null,
  REGDEM_ADD_GEOM_START: null,
  REGDEM_ADD_GEOM_END: null,
  REGDEM_GET_CURRENT_LOCATION: null,
  REGDEM_LOCATION_HAS_BEEN_SET: null,
  REGDEM_GO_BACK_AND_RESET: null
});

module.exports.values = {
  REGDEM_SIZE_DESKTOP: 800
};
